include:
  - board: nice_nano_v2
    shield: charybdis_nano_left
  - board: nice_nano_v2
    shield: charybdis_nano_right

board: [ "nice_nano_v2" ]
shield: [ "charybdis_nano_left", "charybdis_nano_right" ]
